### ISSUE TITLE
#redirectmsg is hidden by default

### ISSUE THREAD

**Issue by sknorr** [SUSEdoc/documentation.suse.com-issues#11]
To actually see the \#redirectmsg, you need to scroll up which is rather suboptimal.

**Comment by asettle** [comment]
Yeahhh - Frank and I just spoke about it. Kinda sad. I would recommend a slight update to the message that says we *are* working on proper redirects, but they will take some time. Or something to that affect.

**Comment by sknorr** [comment]
I don't think we're working on proper redirects... or are we?

**Comment by asettle** [comment]
> I don't think we're working on proper redirects... or are we?

I'll forward you the email from Matt. Perhaps I misunderstood.

**Comment by sknorr** [comment]
Had that one already but thanks, I think you're misunderstanding it though, afaict.

**Comment by asettle** [comment]
Superb. That's not so great.

**Comment by fsundermeyer** [comment]
Redirecting everything is not possible.

**Comment by fsundermeyer** [comment]
@sknorr The redirect message you get when accessing a /+redirectmsg link is hidden, because the page is opened with the headline in focus.

**Comment by sknorr** [comment]
The issue is a bit more tricky, if you add \#anything to the URL, the browser will scroll the page, so \#anything is at the top of the screen. Unfortunately, the page header overlays the top of the screen.

However, we could just change the ID of the actual message, so we don't actually scroll to it. To do that without too much fuzz right now:

1. in [docserv-config]/template-external/res/generatebreadcrumbs.js, replace line 27 with the following two lines:

  ```
      document.getElementById('redirectmsg').id = 'redirect_message';
      document.getElementById('redirect_message').style.display = '';
  ```

2. Then rebuild something simple like sle-vmdp,2.5,en-us.

This renames the ID before the message is made visible. You could also change the message ID directly in the template HTML files but that would mean you'd have to run a regex on all the existing HTML navigation files or rebuild the entire site yet again. So don't do that.

**Comment by sknorr** [comment]
Will be fixed on short order.
