### ISSUE TITLE
public cloud setup guide missing

### ISSUE THREAD

**Issue by jgleissner** [SUSEdoc/documentation.suse.com-issues#23]
The link to the public cloud specific documentation in https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/index.html (Installation Guide -> Setting Up -> Public Cloud Setup) does not work. It seems the section is missing.

**Comment by sknorr** [comment]
@lbrindley @jcayouette @keichwa Could you check on this link in your docs?

**Comment by sknorr** [comment]
This has been fixed in the last SUMA 4.0 documentation update two or so weeks ago.
