### ISSUE TITLE
Categorize the "additional documents" at the bottom of the product doc page 

### ISSUE THREAD

**Issue by chabowski** [SUSEdoc/documentation.suse.com-issues#4]
At the bottom of the product pages there are several documents such as e.g. Release Notes and Best Practices. Can we categorize that? It looks quite unclear currently.

I think Release notes are so important that they deserve their own category.

And the other docs could be listed under a category "Additional Documents" or, if there are many best practices, a category "Best Practices".

**Comment by fsundermeyer** [comment]
Duplicate of https://github.com/openSUSE/docserv/issues/231
